# Modulo assets/templates — SPARK Framework Engine
# Estratto durante Fase 0 refactoring modulare
"""Costanti/marker e template testuali per il rendering Phase 6."""
from __future__ import annotations


_AGENTS_INDEX_BEGIN: str = "<!-- SCF:BEGIN:agents-index -->"
_AGENTS_INDEX_END: str = "<!-- SCF:END:agents-index -->"

_PROJECT_PROFILE_TEMPLATE: str = """---
spark: true
scf_file_role: "config"
scf_owner: "user"
scf_protected: true
---

# Project Profile

> Compila questo file con i dati del progetto. Lo gestisce l'agente
> `spark-welcome`. Dopo modifiche manuali rilancia
> `scf_bootstrap_workspace` per propagare le modifiche agli asset
> derivati (AGENTS.md, .clinerules).

## Identità progetto

- **Nome**:
- **Descrizione breve**:
- **Stack principale**:
- **Linguaggi**:
- **Framework**:

## Convenzioni

- **Stile codice**:
- **Test framework**:
- **Build/Deploy**:

## Pacchetti SCF consigliati

- (compilato da spark-welcome)

## Note

- (libero)
"""


_CLINERULES_TEMPLATE_HEADER: str = """# .clinerules — Generated by spark-framework-engine

> Regole base per agenti Cline / Roo Code. Il file è generato dal
> bootstrap dell'engine e NON sovrascritto se gia' esistente con
> contenuto utente.

"""
